[pytest]


addopts=-vs --reruns 2 --alluredir ./temp/my_allure_results --clean-alluredir
testpaths=./testcase
python_files=test_*.py
python_classes=Test
python_functions=*_link
markers=
    smoke:冒烟用例
    firstleg:头程模块
